### ISSUE TITLE
[question] Geospatial data support

### ISSUE THREAD

**Issue by archenroot** [oreon3D/Oreon.Engine-OpenGL-Java#4]
Hi,

one of my experiment I wanted to use with Oreon for was load of geospatial data for terrain generation, sources like:
http://gisgeography.com/best-free-gis-data-sources-raster-vector/

is there any bridge/generic loader available in some GIS supported way, or you use your own geometry style which means that I will need to implement this bridge (conversion tool)?

Thanks.

**Comment by oreon3D** [comment]
Hi,
no sorry, there is no GIS supported loading yet...

**Comment by archenroot** [comment]
Not a problem, this is just a question in the moment. Thx.

2017-06-20 12:22 GMT+02:00 Fynn <notifications@github.com>:

**Comment by archenroot** [comment]
I will open this later again when I have clear idea about the GIS dataset on input.
