### ISSUE TITLE
[question] Any plans for kind of plugin system?

### ISSUE THREAD

**Issue by archenroot** [oreon3D/Oreon.Engine-OpenGL-Java#6]
Do you plan to support some kind of plugin system?

**Comment by oreon3D** [comment]
plugin is a very a very general term :P what kind plugins do you mean?

**Comment by archenroot** [comment]
@oreon3D geospatial processing. Actually I working on some neural network system which generates point cloud or voxel based graphics just from camera, I would like to take GPS navigates, load the GIS elevation data and render the 3D reconstructed world from video stream directly into exact position on earth.

I have working prototypes, but not sure if I go with Java or with WebGL for rendering. WebGL on one hand will bring easy to access via internet capability which, but backend will be based on Java mostly with CUDA and dozen of other libraries most of them imported via JAVACPP project into Java world, that is why I get here :-) Still deciding and experimenting.
