### ISSUE TITLE
[question] Multiple main methods

### ISSUE THREAD

**Issue by archenroot** [oreon3D/Oreon.Engine-OpenGL-Java#7]
Hi,

I have almost ready the Maven layout. I have little bit problem with main methods for executable JAR generation as there are multiple:
1.
```
package org.oreon.engine.apps.worldgenerator;

import org.oreon.engine.apps.worldgenerator.mainInterface.MainInterface;

public class Main {

	public static void main(String[] args) {
		
		MainInterface.start();
	}

}
```

2.
```
package org.oreon.engine.apps.samples.fractalworlds;

import org.oreon.engine.engine.core.Game;
import org.oreon.engine.modules.atmosphere.SkySphere;
import org.oreon.engine.modules.terrain.Terrain;

public class FractalWorlds {
	
	public static void main(String[] args) {
```		

3.
```
package org.oreon.engine.apps.oreonworlds;

import org.oreon.engine.apps.oreonworlds.assets.plants.Bush01ClusterGroup;
import org.oreon.engine.apps.oreonworlds.assets.plants.Grass01ClusterGroup;
import org.oreon.engine.apps.oreonworlds.assets.plants.Palm01ClusterGroup;
import org.oreon.engine.apps.oreonworlds.assets.plants.Plant01ClusterGroup;
import org.oreon.engine.apps.oreonworlds.assets.plants.Tree01ClusterGroup;
import org.oreon.engine.apps.oreonworlds.assets.plants.Tree02ClusterGroup;
import org.oreon.engine.apps.oreonworlds.assets.rocks.Rock01ClusterGroup;
import org.oreon.engine.apps.oreonworlds.assets.rocks.Rock02ClusterGroup;
import org.oreon.engine.apps.oreonworlds.gui.GUI;
import org.oreon.engine.apps.oreonworlds.shaders.terrain.TerrainGridShader;
import org.oreon.engine.apps.oreonworlds.shaders.terrain.TerrainShader;
import org.oreon.engine.apps.oreonworlds.water.Ocean;
import org.oreon.engine.apps.worldgenerator.tools.terrainEditor.TerrainShadowShader;
import org.oreon.engine.engine.core.Game;
import org.oreon.engine.modules.atmosphere.SkySphere;
import org.oreon.engine.modules.atmosphere.Sun;
import org.oreon.engine.modules.terrain.Terrain;

public class Main {

	public static void main(String[] args) {
```
		
4.
```
package org.oreon.engine.apps.samples.ocean;

import org.oreon.engine.apps.samples.ocean.gui.GUI;
import org.oreon.engine.engine.core.Game;
import org.oreon.engine.modules.atmosphere.SkySphere;
import org.oreon.engine.modules.atmosphere.Sun;

public class OceanSimulation {

	public static void main(String[] args) {
```

5.
```
package org.oreon.engine.apps.samples.objLoader;

import org.oreon.engine.engine.core.Game;
import org.oreon.engine.modules.gui.GUIs.VoidGUI;


public class Main{

public static void main(String[] args) {
```
Which one is the correct one, or should I generate 5 JARs in the moment. Maybe it will be good to provide some GUI later, something like:
http://vrl-studio.mihosoft.eu/

And implement Ocean, fractal worlds or generator as kind of Nodes (coming from node based visual programming), just hints for possible future path to discuss.

http://blog.interfacevision.com/design/design-visual-progarmming-languages-snapshots/

**Comment by oreon3D** [comment]
the main methods are different applications/simulations or games. You can delete the objLoader, it was just for testing.
oreonworlds.main is the actual terrain simulation with all features. For different simulations, different maven builds are needed I guess. The package oreon.engine.apps is for sample simulations with executables. I think I will rename some of it the classes/packages in oreon.engine.apps soon to prevent confusion...
oreon.engine.engine is the kernel of the engine (GPU buffer allocation, 3D math, shader creation, scenegraph etc.) .
oreon.engine.modules are all the supported features like post processing effects, shadow mapping, FFT water etc. .

Yeah that GUI-API form vrl-studio looks very nice, it could be used for an editor as an extention to create a game/simulation.

Ocean, Fractalworlds and worldgenerator are different applications as I said. But the node representation is useful for visualization an application itself, that's a good hint.

**Comment by archenroot** [comment]
ad methods: it is clear
I will implement command line switch, so we can have just one which will start each game/scene/world by input

ad vrl-studio: same idea here

Thx.
